apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-

resources:
  - ../../application

patches:
  - target:
      kind: Gateway
      name: gateway
    patch: |-
      - op: replace
        path: /spec/gatewayClassName
        value: dev-gateway-class
  - target:
      kind: HTTPRoute
      name: router
    patch: |-
      - op: replace
        path: /spec/parentRefs/0/name
        value: dev-gateway
      - op: replace
        path: /spec/rules/0/backendRefs/0/name
        value: dev-blog-app-service
  - target:
      kind: ConfigMap
      name: kustom-config
    patch: |-
      - op: replace
        path: /data/MONGO_URI
        value: "mongodb://dev-mongo-service:27017/blogging"      