apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-app-deployment
  namespace: kustom
  labels:
    app: blog-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-app
  template:
    metadata:
      labels:
        app: blog-app
    spec:
      containers:
        - name: blog-app-container
          image: rks007/kustomize:6dc1d7515793065324ee77e94f5f67f1c8776022
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: kustom-config