apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rks007/kubernetes-cicd-lab.git
    targetRevision: HEAD
    path: kubernetes/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-kustom
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true