apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-

resources:
  - ../../application
  - hpa.yml
patches:
  - path: resources-patch.yml
    target:
      kind: Deployment
      name: blog-app-deployment
  - target:
      kind: Gateway
      name: gateway
    patch: |-
      - op: replace
        path: /spec/gatewayClassName
        value: prod-gateway-class
  - target:
      kind: HTTPRoute
      name: router
    patch: |-
      - op: replace
        path: /spec/parentRefs/0/name
        value: prod-gateway
      - op: replace
        path: /spec/rules/0/backendRefs/0/name
        value: prod-blog-app-service
