apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - hpa.yaml
patches:
  - path: resources-patch.yaml
    target:
      kind: Deployment
      name: blog-app-deployment